server:
  port: 8081


logging:
  level:
    org:
      springframework:
        web: DEBUG

github:
  url:
    repositories: https://api.github.com/users/{USER_NAME}/repos
    branches: https://api.github.com/repos/{USER_NAME}/{REPO_NAME}/branches

#  Github gives more rate limit if we the request is authorized, so i prefered to use public scope token because of not getting rate limit error
#  Please put your public read only access token which created in github
  bearer-token: <access_token>